warp-ds/css-docs

docs/global-components/Box.vue
docs/margin/index.md
docs/padding/index.md

Add margin docs

---

docs/space-between/index.md

These classes dont seam to be working yet, but they will eventually ;) Might need to be updated when they are ready from the warp drive.

Add space-between docs

---

docs/.vitepress/config.js
docs/flex-basis/index.md
docs/flex-direction/index.md
docs/flex-grow/index.md
docs/flex-shrink/index.md
docs/flex-wrap/index.md
docs/flex/index.md
docs/global-components/Box.vue

**All the flex- prefixed stuff**
Flex
Flex-basis
Flex-direction
Flex-grow
Flex-shrink
Flex-wrap

Add flex docs

---

docs/.vitepress/config.js
docs/gap/index.md
docs/grid-auto-columns/index.md
docs/grid-auto-flow/index.md
docs/grid-auto-rows/index.md
docs/grid-column-se/index.md
docs/grid-row-se/index.md
docs/grid-template-columns/index.md
docs/grid-template-rows/index.md
docs/order/index.md

Order
Grid temp Columns
Grid Column start/end
Grid Template Rows
Grid Rows Start / End
Grid Auto Flow
Grid Auto Columns
Grid Auto Rows
Gap

Add grid docs

---

docs/.vitepress/config.js
docs/height.md
docs/width.md

Add docs for height and width

---

docs/max-height.md
docs/max-width.md
docs/min-height.md
docs/min-width.md

As we will have a separate page for the docs for the arbitrary values where we will provide specifics for those values let's keep the values for min-/max-width/height simple.

Keep numbers for max min width and height

---

docs/unocss.config.js
docs/vite.config.js
package.json
pnpm-lock.yaml

Only lints JS files, but at least is consistent with other projects now!

Set up linting

---

docs/.vitepress/config.js
docs/global-components/Container.vue
docs/top-right-bottom-left.md

Top, Right, bottom, left, inset 
+small adjustment to Container comp

Add placement docs

---

docs/.vitepress/config.js
docs/visibility.md
docs/z-index.md

Docs for z-index and Visibility 

---

docs/.vitepress/config.js
docs/border-color.md
docs/border-radius.md
docs/border-width.md

border-radius
border-width
border-color

Add borderific docs

---

docs/.vitepress/config.js
docs/content.md
docs/font-size.md
docs/font-style.md
docs/font-variant-numeric.md
docs/line-height.md
docs/text-align.md
docs/text-color.md
docs/text-decoration.md
docs/text-overflow.md
docs/text-transform.md
docs/vertical-align.md
docs/whitespace.md
docs/word-break.md

font-size
font-style
font Variant Numeric
line height
text align
text color
text decoration
text transform
text overflow
vertical align
whitespace
word break
content

Add some typography docs

---

docs/.vitepress/config.js
docs/background-image.md
docs/classes.list.js
docs/screen-readers.md

Add screen reader docs

---

docs/.vitepress/config.js
docs/classes.list.js
docs/rotate.md
docs/scale.md
docs/skew.md
docs/transform-origin.md
docs/translate.md

Scale
Rotate
Translate
Skew
Transform Origin

Add transform docs

---

docs/align-content.md
docs/align-items.md
docs/align-self.md
docs/flex-basis.md
docs/flex-direction.md
docs/flex-grow.md
docs/flex-shrink.md
docs/flex-wrap.md
docs/flex.md
docs/gap.md
docs/global-components/WidthController.vue
docs/grid-auto-flow.md
docs/grid-column-se.md
docs/grid-row-se.md
docs/grid-template-columns.md
docs/grid-template-rows.md
docs/justify-content.md
docs/justify-items.md
docs/justify-self.md
docs/margin.md
docs/order.md
docs/padding.md
docs/place-content.md
docs/place-items.md
docs/place-self.md
docs/space-between.md
docs/unocss.config.js

Applies the same rounded corners and shadows to examples to make them tie together a little better...

Nicer more coherent docs

---

docs/.vitepress/border-spacing.md
docs/.vitepress/config.js
docs/border-collapse.md
docs/border-spacing.md
docs/classes.list.js
docs/table-layout.md
package.json
pnpm-lock.yaml

border-collapse
border-spacing
Table layout

docs: Add table docs + bump vitepress

---

docs/.vitepress/config.js
docs/classes.list.js
docs/transition-delay.md
docs/transition-duration.md
docs/transition-property.md
docs/transition-timing.md

Transition Property
Transition Duration
Transition Timing
Transition Delay

docs: Add transition stuff

---

docs/.vitepress/config.js
docs/appearance.md
docs/classes.list.js
docs/cursor.md
docs/pointer-events.md
docs/resize.md
docs/scroll-behavior.md
docs/scroll-snap-align.md
docs/scroll-snap-stop.md
docs/scroll-snap-type.md
docs/touch-action.md
docs/transition-delay.md
docs/transition-duration.md
docs/user-select.md
docs/will-change.md

Appearance
Cursor
Pointer Events
Resize
Scroll Behavior
Scroll Snap Align
Scroll Snap Stop
Scroll Snap Type
Touch Action
User Select
Will Change

docs: Add Interactivity docs + fix some typos

---

docs/.vitepress/config.js
docs/animation.md
docs/classes.list.js
package.json
pnpm-lock.yaml

docs: add animate-inprogress

---

docs/.vitepress/config.js
docs/classes.list.js
docs/opacity.md

Add docs for opacity

---

docs/.vitepress/config.js
docs/caret.md
docs/classes.list.js
package.json
pnpm-lock.yaml

It a little bit weird maybe how this uses a 'component specific' variable to set a default. Prob the caret color should instead be a general default token, like just 'color-caret' that is giventhe caret color pr.brand ?   (as it looks in the spreadsheet now it looks like it is ment to generate a i-color-$ kind of class, thats maybe not needed forthis(?))

Add docs for caret color

---

package.json

To test prod build:
`pnpm run build && pnpm run preview`

fix:add script to preview prod build

---

docs/.vitepress/config.js

fix: we need resets from drive

---

docs/.vitepress/config.js
docs/.vitepress/theme/custom.css
package.json
pnpm-lock.yaml

fix: remove algolia search and replace with vitepress one

---

docs/.vitepress/config.js
docs/.vitepress/customElements/background-color-example.js
docs/.vitepress/theme/index.js
docs/background-color.md
docs/border-color.md
docs/classes.js
docs/classes.list.js
docs/global-components/ThemeContainer.vue
docs/global-components/qr-color-table.vue
docs/text-color.md
package.json
pnpm-lock.yaml

fix: add semantic tokens for color classes

---

docs/border-width.md

Issue was reported here https://github.com/warp-ds/drive/issues/117

fix: add px to the supported border rules

---

docs/getting-started.md

Mention other ways of adding UnoCSS stylesheet to the project as suggested in https://github.com/warp-ds/tech-docs/pull/81

fix: improve instruction for adding uno.css

---

docs/getting-started.md
docs/plugin-api.md

- Align with UnoCSS setup based on https://warp-ds.github.io/tech-docs/getting-started/developers/
- Recommend `@warp-ds/uno@1.0.0-alpha.49` for current tokens
- update presetWarp plugin API based on https://github.com/warp-ds/drive#readme

fix: stable finn prod @versions

---

.gitignore
docs/.vitepress/customElements/fontsize-example.js
docs/classes.list.js
package.json
pnpm-lock.yaml

[WARP-121](https://nmp-jira.atlassian.net/browse/WARP-121) Bump uno and update css docs after https://github.com/warp-ds/drive/pull/135 + some cleanup

Update css docs

---

docs/aspect-ratio.md
docs/border-radius.md
docs/margin.md
docs/top-right-bottom-left.md
docs/will-change.md

(typos, bugs, structure, layout and removal of tailwind references)

Misc cleanup 

---

docs/border-color.md

(mostly info about arbitrary values)

Update documentation for border color 

---

docs/.vitepress/theme/index.js
docs/background-color.md
docs/border-color.md
docs/divide-color.md
docs/global-components/qr-color-table.vue
docs/icon-color.md
docs/outline-color.md
docs/text-color.md
package.json
pnpm-lock.yaml

- Update dependencies (including new things for icons, css and uno)
- Add missing documentation for icon color
- Add documentation for new alpha channel modifier to all color classes
- Improve info on s-prefix

Update docs for color classes

---

docs/.vitepress/theme/custom.css
docs/animation.md

Update documentation for inprogress and spinner animations

---

docs/aspect-ratio.md
docs/border-radius.md
docs/border-spacing.md
docs/border-width.md
docs/box-shadow.md
docs/divide-style.md
docs/divide-width.md
docs/font-weight.md
docs/margin.md
docs/max-width.md
docs/outline-offset.md
docs/outline-style.md
docs/outline-width.md
docs/padding.md
docs/rotate.md
docs/scale.md
docs/skew.md
docs/space-between.md
docs/text-overflow.md
docs/transition-delay.md
docs/transition-duration.md
docs/translate.md

Cleaning up:
- visual code examples
- faulty code in examples
- wrong info in wrong places
- duplicated things
- unescaped "{" / "}"
- table layouts
- typos
- document structure
-  ...

Cleaning up a lot of things
